### PR TITLE
feat: add prefix option

### PR DESCRIPTION
**Pull request by afzaalahmad**
Add a prefix option inside PluginOptions for user being able to upload images to a specific folder inside the cloud storage.

### CODE REVIEW

**Comment by jmikrut** [comment]
@afzaalahmad this is absolutely amazing.

We are going to review this shortly and then cut a release. At first glance, I see nothing that needs to be changed in the PR. We just need to look through manually a bit further, and then you can expect this released shortly!

THANK YOU!

**Comment by DanRibbens** [comment]
I was able to test both Azure and AWS S3.
I did not test GCS.

The changes appear to work as intended. My only comment is that the term `prefix` might be strange.
Before reading too deep into it I had assumed it was going to actually prefix to the folder, but it really is a way to add folders, not rename them.
Could just be me, but "folder" or "path" might be more semantic names for what this feature is doing.
Thoughts?

**Comment by afzaalahmad** [comment]
@jmikrut @denolfe  Thank you for quick review. Sure, I understand that you want to test it throughly before release, so I am going to list out my reasoning of exact implementation of prefix in this specific way.

I've added the prefix in the document of `upload` collection and the purpose of doing this is to save the prefix for that specific image to be used in future for `deletion` and `read` purposes if user changes the prefix inside configuration. In that case, already uploaded images will not get effected, and new images will also get uploaded.

Also, I've test GCS, and AWS with real buckets, and all three of them in emulators.

**Review by DanRibbens — COMMENTED** [review]
LGTM,

See comment: 
https://github.com/payloadcms/plugin-cloud-storage/pull/5#issuecomment-1226456061

**Comment by afzaalahmad** [comment]
@DanRibbens I agree. It can be `path`but folder might not be a good term. But `prefix` is also something that can be used because in these cloud storage buckets, they don't call it directory. They consider the whole path as a filename.
Look at this: https://serverfault.com/questions/435827/what-is-the-difference-between-buckets-and-folders-in-amazon-s3

**Comment by DanRibbens** [comment]
> @DanRibbens I agree. It can be `path`but folder might not be a good term. But `prefix` is also something that can be used because in these cloud storage buckets, they don't call it directory. They consider the whole path as a filename. Look at this: https://serverfault.com/questions/435827/what-is-the-difference-between-buckets-and-folders-in-amazon-s3

Thats a perfect explanation, thanks. I'll go ahead and get it merged and released. Thanks taking this!

**Review by DanRibbens — APPROVED** [review]
Great work!

**Pull request merged**
